FROM golang:1.20-alpine as builder
RUN apk --no-cache add git gcc libc-dev linux-headers
WORKDIR /go/src/ssb-rpc-client
COPY . .
RUN    export CGO_ENABLED=1 \
    && mkdir -p dist \
    && go mod vendor \
    && go build -o dist/ssb-rpc-client ./cmd/ssb-rpc-client

FROM alpine:3.16
RUN apk --no-cache add ca-certificates bash
WORKDIR /root
COPY --from=builder /go/src/ssb-rpc-client/dist/ /usr/local/bin/
CMD ["/usr/local/bin/ssb-rpc-client"]
