FROM golang:1.20-alpine as builder
RUN apk --no-cache add git gcc libc-dev linux-headers
WORKDIR /go/src/leeloo
COPY . .
RUN    export CGO_ENABLED=1 \
    && mkdir -p dist \
    && go mod vendor \
    && go build -o dist/leeloo ./cmd/leeloo

FROM alpine:3.16
RUN apk --no-cache add ca-certificates
WORKDIR /root
COPY --from=builder /go/src/leeloo/dist/ /usr/local/bin/
COPY ./config.hcl ./config.hcl
ENTRYPOINT ["/usr/local/bin/leeloo"]
