FROM golang:1.18-alpine as builder
RUN apk --no-cache add git gcc libc-dev linux-headers
WORKDIR /go/src/leeloo
COPY . .
RUN    export CGO_ENABLED=1 \
    && mkdir dist \
    && go mod vendor \
    && go build -o dist/leeloo ./cmd/leeloo

FROM alpine:3.14
RUN apk --no-cache add ca-certificates
WORKDIR /root
COPY --from=builder /go/src/leeloo/dist/ /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/leeloo"]
