name: Build & Publish DEV Docker Images
# Build & Push rebuilds the tendermint docker image on every push to master and creation of tags
# and pushes the image to https://hub.docker.com/r/interchainio/simapp/tags
on:
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker image with all binaries
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/chronicleprotocol/oracle-suite:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker image for Gofer
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile-gofer
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/chronicleprotocol/gofer:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker image for Spire
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile-spire
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/chronicleprotocol/spire:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Docker image for Ghost
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile-ghost
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/chronicleprotocol/ghost:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker image for Spectre
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile-spectre
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/chronicleprotocol/spectre:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker image for LeeLoo
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile-leeloo
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/chronicleprotocol/leeloo:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker image for Lair
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile-lair
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/chronicleprotocol/lair:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker image for RPC Splitter
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile-rpc-splitter
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/chronicleprotocol/rpc-splitter:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Docker image for SSB RPC Client
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile-ssb-rpc-client
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/chronicleprotocol/ssb-rpc-client:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max
